/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/apple": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signInWithApple"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["requestAccountDeletion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/resident": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getResident"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateResident"];
        trace?: never;
    };
    "/resident/mini": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateMini"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/world/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWorldBootstrap"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cities/{cityId}/chunks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCityChunks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/plots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getClaimablePlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reservePlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plots/{plotId}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["claimPlot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{propertyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProperty"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{propertyId}/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updatePropertyAccess"];
        trace?: never;
    };
    "/spaces/{spaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSpace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceId}/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["replaceSpaceLayout"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{propertyId}/visit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Transient, non-live observation. Call on entering and again after the dwell threshold (e.g. on leaving); the server measures dwell and qualifies at most one visit per visitor/property/day. The owner only ever sees anonymous aggregates. */
        post: operations["visitProperty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceId}/stay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startStay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["endStay"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["leaveGift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["blockResident"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blocks/{residentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["unblockResident"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reportContent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInventory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getWallet"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["purchaseStoreListing"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/spaces/{spaceId}/stays/{residentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Property owner ends a resident active Stay in this space. This is a safety/control action and sends no message. */
        delete: operations["sendStayerHome"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gifts/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGiftInbox"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gifts/{giftId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveGift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cities/{cityId}/roads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Active public road graph and civic anchors for client-side routing (A*). ETag is keyed to the city activation revision; send If-None-Match to get 304. */
        get: operations["getCityRoads"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wander": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description A few publicly enterable homes, nearest-first with jitter. Not a ranking; never includes the caller, blocked residents, or closed homes. */
        get: operations["wander"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties/{propertyId}/visits/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Owner-only anonymous visit aggregate for the last 7 days, in soft-language bands. Exact counts appear only when the visits.exact_counts experiment flag is on. Never exposes visitor identity. */
        get: operations["getVisitSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppleAuthRequest: {
            identity_token: string;
            authorization_code: string;
            nonce: string;
            device_label?: string;
        };
        AuthResponse: {
            access_token: string;
            refresh_token: string;
            expires_in: number;
            /** Format: uuid */
            user_id: string;
            is_new_account: boolean;
        };
        MeResponse: {
            /** Format: uuid */
            user_id: string;
            /** @enum {string} */
            account_status: "active" | "suspended" | "deleting" | "deleted";
            resident?: components["schemas"]["Resident"];
            active_stay?: {
                /** Format: uuid */
                id?: string;
                /** Format: uuid */
                space_id?: string;
                /** Format: uuid */
                host_property_id?: string;
                /** Format: date-time */
                started_at?: string;
            };
        };
        Resident: {
            /** Format: uuid */
            id: string;
            display_name: string;
            public_tag: string;
            mini_definition: {
                [key: string]: unknown;
            };
            /** @enum {string} */
            onboarding_state: "choosing_plot" | "claimed" | "complete";
            primary_home?: {
                /** Format: uuid */
                property_id?: string;
                /** Format: uuid */
                space_id?: string;
                /** Format: uuid */
                plot_id?: string;
                /** Format: uuid */
                city_id?: string;
            };
        };
        WorldBootstrap: {
            /** Format: uuid */
            world_id: string;
            rules_version: number;
            cities: {
                /** Format: uuid */
                id: string;
                display_name: string;
                status: string;
                /** Format: int64 */
                activation_revision?: number;
                theme?: string | null;
            }[];
            asset_packs: {
                pack_id?: string;
                version?: number;
                /** Format: uri */
                manifest_url?: string;
                sha256?: string;
            }[];
            features: {
                [key: string]: unknown;
            };
            coordinate_system?: {
                units_per_tile?: number;
                chunk_size_u?: number;
            };
        };
        ChunkSummary: {
            /** Format: uuid */
            id: string;
            x: number;
            y: number;
            /** Format: int64 */
            revision: number;
            plots: components["schemas"]["PlotSummary"][];
            properties: components["schemas"]["PropertyPreview"][];
        };
        PlotSummary: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "latent" | "vacant" | "reserved" | "occupied" | "retired";
            center_x_u: number;
            center_y_u: number;
            terrain_type: string;
            zone_type: string;
            scenic_tags?: string[];
            build_bounds?: {
                [key: string]: unknown;
            };
            chunk_x?: number;
            chunk_y?: number;
            /** @description Quiet map facts, never a recommendation score. */
            labels?: ("closer_to_town" | "near_park" | "near_neighbors" | "quieter_edge" | "forest_side")[];
            reserved_by_me?: boolean;
            /**
             * Format: uuid
             * @description Public road node this plot fronts; route here for travel animation.
             */
            frontage_node_id?: string;
        };
        PropertyPreview: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            plot_id: string;
            structure_asset_id: string;
            /** @enum {string} */
            access_mode: "open" | "closed";
            has_active_stayers?: boolean;
            /** @enum {string} */
            away_access_mode: "open" | "closed";
            structure_x_u?: number;
            structure_y_u?: number;
            structure_rot_q?: number;
        };
        Property: components["schemas"]["PropertyPreview"] & {
            /** Format: uuid */
            owner_resident_id: string;
            allow_stays: boolean;
            stay_capacity: number;
            is_primary_home?: boolean;
            /** Format: int64 */
            revision: number;
            /** @enum {string} */
            property_type?: "home" | "studio" | "shop" | "other";
            owner?: {
                /** Format: uuid */
                id?: string;
                display_name?: string;
            };
            space_ids?: string[];
            viewer?: {
                is_owner?: boolean;
                can_enter?: boolean;
                can_stay?: boolean;
            };
            /** @description Owner-only: true while the owner has an active foreign Stay. */
            owner_away?: boolean;
        };
        Space: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            property_id: string;
            /** Format: int64 */
            layout_revision: number;
            visitor_capacity: number;
            placements: components["schemas"]["Placement"][];
            space_kind?: string;
            bounds?: {
                minX?: number;
                minY?: number;
                maxX?: number;
                maxY?: number;
            };
            /** @description Active Stays (public presence). Residents in a block relationship with the viewer are omitted. */
            stayers?: components["schemas"]["Stayer"][];
            /** @description Owner only. */
            pending_gifts?: components["schemas"]["PendingGiftPreview"][];
        };
        PlacementInput: {
            /** Format: uuid */
            item_instance_id: string;
            x_u: number;
            y_u: number;
            rotation_q: number;
            /** @default 1000 */
            scale_milli: number;
            /** @default 0 */
            layer: number;
        };
        Placement: components["schemas"]["PlacementInput"] & {
            /** Format: uuid */
            id?: string;
            asset_id?: string;
            definition_key?: string;
        };
        ItemInstance: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            definition_id: string;
            state: string;
            provenance?: {
                [key: string]: unknown;
            };
            definition_key?: string;
            asset_id?: string;
            category?: string;
            gift_eligible?: boolean;
        };
        Gift: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            giver_resident_id: string;
            /** Format: uuid */
            recipient_resident_id: string;
            /** Format: uuid */
            item_instance_id: string;
            /** @enum {string} */
            status: "pending_placement" | "kept_here" | "put_away" | "declined";
            /** Format: date-time */
            created_at: string;
            /** Format: uuid */
            property_id: string;
            /** Format: uuid */
            space_id: string;
            drop_x_u: number;
            drop_y_u: number;
            /** Format: date-time */
            resolved_at?: string;
            /** @description Intentional identity reveal. linkable=false after block or deletion. */
            giver?: {
                display_name?: string;
                linkable?: boolean;
            };
            asset_id?: string;
            definition_key?: string;
        };
        Wallet: {
            currency_code: string;
            /** Format: int64 */
            balance: number;
        };
        StoreListing: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            item_definition_id: string;
            /** Format: int64 */
            unit_price: number;
            /** Format: int64 */
            stock_quantity?: number;
            /** @enum {string} */
            status: "active" | "paused" | "sold_out" | "ended";
            definition_key?: string;
            asset_id?: string;
            category?: string;
            gift_eligible?: boolean;
        };
        MutationResponse: {
            request_id: string;
            /** Format: int64 */
            revision?: number;
            /** Format: uuid */
            resource_id?: string;
        };
        ErrorResponse: {
            request_id: string;
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        Stayer: {
            /** Format: uuid */
            resident_id: string;
            display_name: string;
            mini_definition: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            started_at: string;
        };
        PendingGiftPreview: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            item_instance_id?: string;
            drop_x_u?: number;
            drop_y_u?: number;
            asset_id?: string;
            definition_key?: string;
        };
        RoadGraph: {
            /** Format: uuid */
            city_id: string;
            /** Format: int64 */
            activation_revision: number;
            nodes: {
                /** Format: uuid */
                id: string;
                x_u: number;
                y_u: number;
                node_kind: string;
            }[];
            edges: {
                /** Format: uuid */
                id: string;
                /** Format: uuid */
                from_node_id: string;
                /** Format: uuid */
                to_node_id: string;
                edge_kind?: string;
                weight_milli: number;
                geometry_points?: {
                    x_u?: number;
                    y_u?: number;
                }[];
            }[];
            civic_anchors: {
                /** Format: uuid */
                id?: string;
                kind?: string;
                x_u?: number;
                y_u?: number;
                /** Format: uuid */
                road_node_id?: string;
            }[];
        };
    };
    responses: {
        /** @description Authentication required or invalid. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authenticated but operation is not allowed. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found or intentionally hidden. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description State conflict, duplicate/race, stale revision, or idempotency mismatch. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request failed validation/business rules. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
        IdempotencyKey: string;
        CityId: string;
        PlotId: string;
        PropertyId: string;
        SpaceId: string;
        ResidentId: string;
        GiftId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signInWithApple: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppleAuthRequest"];
            };
        };
        responses: {
            /** @description Authenticated existing account. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Created a new account. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refresh_token: string;
                };
            };
        };
        responses: {
            /** @description Session refreshed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: {
                /** @description Revoke every session of this account (all devices). */
                all?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current account and resident summary. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    requestAccountDeletion: {
        parameters: {
            query?: never;
            header: {
                /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deletion requested; account removed from public discovery immediately. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getResident: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current resident profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resident"];
                };
            };
        };
    };
    updateResident: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    display_name?: string;
                };
            };
        };
        responses: {
            /** @description Updated resident. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resident"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    updateMini: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    definition: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Updated Mini definition. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resident"];
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getWorldBootstrap: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description World, founding-city, feature flag, and asset-pack bootstrap data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldBootstrap"];
                };
            };
        };
    };
    getCityChunks: {
        parameters: {
            query: {
                minX: number;
                minY: number;
                maxX: number;
                maxY: number;
            };
            header?: never;
            path: {
                cityId: components["parameters"]["CityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dynamic state for requested chunk window only. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        chunks: components["schemas"]["ChunkSummary"][];
                    };
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getClaimablePlots: {
        parameters: {
            query: {
                city_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All currently active claimable plots in the onboarding city scope. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        plots: components["schemas"]["PlotSummary"][];
                    };
                };
            };
        };
    };
    reservePlot: {
        parameters: {
            query?: never;
            header: {
                /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                plotId: components["parameters"]["PlotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short-lived reservation created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"] & {
                        /** Format: uuid */
                        reservation_id?: string;
                        /** Format: date-time */
                        expires_at?: string;
                    };
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    claimPlot: {
        parameters: {
            query?: never;
            header: {
                /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                plotId: components["parameters"]["PlotId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    reservation_id: string;
                    structure_asset_id: string;
                    /** @default 0 */
                    structure_x_u?: number;
                    /** @default 0 */
                    structure_y_u?: number;
                    structure_rot_q?: number;
                };
            };
        };
        responses: {
            /** @description Plot claimed and starter property created atomically. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"] & {
                        property?: components["schemas"]["Property"];
                    };
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public/owner-authorized property state. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updatePropertyAccess: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    access_mode?: "open" | "closed";
                    allow_stays?: boolean;
                    stay_capacity?: number;
                    /** Format: int64 */
                    expected_revision?: number;
                    /** @enum {string} */
                    away_access_mode?: "open" | "closed";
                };
            };
        };
        responses: {
            /** @description Access policy updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Property"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getSpace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spaceId: components["parameters"]["SpaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Space and canonical placements. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Space"];
                };
            };
        };
    };
    replaceSpaceLayout: {
        parameters: {
            query?: never;
            header: {
                /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                spaceId: components["parameters"]["SpaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: int64 */
                    expected_revision: number;
                    placements: components["schemas"]["PlacementInput"][];
                };
            };
        };
        responses: {
            /** @description Canonical layout saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Space"];
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    visitProperty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Visit authorized. Owner never receives visitor identity from ordinary visit history. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request_id: string;
                        property: components["schemas"]["Property"];
                        spaces: components["schemas"]["Space"][];
                        visit?: {
                            qualified?: boolean;
                        };
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    startStay: {
        parameters: {
            query?: never;
            header: {
                /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                spaceId: components["parameters"]["SpaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persistent asynchronous Stay started. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"] & {
                        /** Format: uuid */
                        stay_id?: string;
                    };
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    endStay: {
        parameters: {
            query?: never;
            header: {
                /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current active Stay ended. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
        };
    };
    leaveGift: {
        parameters: {
            query?: never;
            header: {
                /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    property_id: string;
                    /** Format: uuid */
                    space_id: string;
                    /** Format: uuid */
                    item_instance_id: string;
                    drop_x_u: number;
                    drop_y_u: number;
                };
            };
        };
        responses: {
            /** @description Gift ownership transferred atomically and awaits recipient placement decision. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gift"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
        };
    };
    blockResident: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    resident_id: string;
                };
            };
        };
        responses: {
            /** @description Resident blocked; prohibited active interactions are terminated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    unblockResident: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                residentId: components["parameters"]["ResidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resident unblocked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reportContent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    target_type: "resident" | "property" | "item";
                    /** Format: uuid */
                    target_id: string;
                    reason_code: string;
                    details?: string;
                };
            };
        };
        responses: {
            /** @description Report accepted. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
        };
    };
    getInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current canonical inventory. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ItemInstance"][];
                    };
                };
            };
        };
    };
    getWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current materialized balance and currency code. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wallet"];
                };
            };
        };
    };
    getCatalog: {
        parameters: {
            query?: {
                city_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active system/city listings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        listings?: components["schemas"]["StoreListing"][];
                    };
                };
            };
        };
    };
    purchaseStoreListing: {
        parameters: {
            query?: never;
            header: {
                /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    listing_id: string;
                    quantity: number;
                };
            };
        };
        responses: {
            /** @description Purchase posted atomically. Server decides canonical price/balance. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        request_id: string;
                        /** Format: uuid */
                        transaction_id: string;
                        wallet: components["schemas"]["Wallet"];
                        items: components["schemas"]["ItemInstance"][];
                    };
                };
            };
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    sendStayerHome: {
        parameters: {
            query?: never;
            header: {
                /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                spaceId: components["parameters"]["SpaceId"];
                residentId: components["parameters"]["ResidentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stay ended and resident durable presence returned to primary home. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MutationResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listGiftInbox: {
        parameters: {
            query?: {
                status?: "pending_placement" | "kept_here" | "put_away" | "declined";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gifts addressed to the authenticated resident. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Gift"][];
                    };
                };
            };
        };
    };
    resolveGift: {
        parameters: {
            query?: never;
            header: {
                /** @description Scoped to (user, operation). Same key + same request replays the stored response; same key + different request is 409 idempotency_mismatch. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                giftId: components["parameters"]["GiftId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    action: "keep_here" | "put_away" | "decline";
                };
            };
        };
        responses: {
            /** @description Gift resolved atomically. Decline returns the item to giver inventory when possible. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gift"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getCityRoads: {
        parameters: {
            query?: never;
            header?: {
                "If-None-Match"?: string;
            };
            path: {
                cityId: components["parameters"]["CityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Active road graph. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadGraph"];
                };
            };
            /** @description Unchanged since the given ETag. */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    wander: {
        parameters: {
            query: {
                city_id: string;
                x_u?: number;
                y_u?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wander candidates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        properties: (components["schemas"]["PropertyPreview"] & {
                            center_x_u?: number;
                            center_y_u?: number;
                            /** Format: uuid */
                            frontage_node_id?: string;
                        })[];
                    };
                };
            };
            422: components["responses"]["ValidationError"];
        };
    };
    getVisitSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                propertyId: components["parameters"]["PropertyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-language aggregate. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        property_id: string;
                        window_days?: number;
                        /** @enum {string} */
                        band: "none" | "someone" | "a_few" | "busy";
                        copy: string;
                        count?: number;
                        days: {
                            /** Format: date */
                            day?: string;
                            band?: string;
                            count?: number;
                        }[];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
}
