// Regenerate typed Drizzle tables from a migrated database, then patch known drizzle-kit gaps.
// Usage: DATABASE_URL=... node scripts/drizzle-pull.mjs
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, rmSync, existsSync } from 'node:fs';

execSync('npx drizzle-kit pull', { stdio: 'inherit' });
const dir = 'packages/db/src/generated';
for (const f of ['meta']) if (existsSync(`${dir}/${f}`)) rmSync(`${dir}/${f}`, { recursive: true });
for (const f of (await import('node:fs')).readdirSync(dir)) if (f.endsWith('.sql')) rmSync(`${dir}/${f}`);
const p = `${dir}/schema.ts`;
let s = readFileSync(p, 'utf8');
s = s.replace(/\t\/\/ TODO: failed to parse database type 'bytea'\n/g, '').replace(/unknown\("/g, 'bytea("');
s = s.replace(
  'import { sql } from "drizzle-orm"',
  'import { sql } from "drizzle-orm"\nimport { customType } from "drizzle-orm/pg-core"\n\n// drizzle-kit cannot introspect bytea\nconst bytea = customType<{ data: Uint8Array }>({ dataType: () => "bytea" })',
);
writeFileSync(p, '// GENERATED by scripts/drizzle-pull.mjs from db/migrations. Do not edit by hand.\n' + s);
console.log('patched', p);
